# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeworkAssistant' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HomeworkAssistant
	pod 'RDVTabBarController'
	pod 'Masonry'
	pod 'SDWebImage'
	pod 'AFNetworking'
	pod 'MBProgressHUD'
    	pod 'UMCCommon'
    	pod 'UMCSecurityPlugins'
	pod 'UMCShare/UI'
	pod 'UMCShare/Social/ReducedWeChat'
	pod 'UMCShare/Social/ReducedQQ'
	pod 'WechatOpenSDK'
	pod 'SGQRCode'
	pod 'MJRefresh'
	pod 'PYSearch'
#    pod 'JXCategoryView'
	pod 'XWHUDManager'
end
